In [170]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [171]:
df = pd.read_csv('loan_approval_data.csv')

In [172]:
df.head()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,NaN,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_ID        950 non-null    float64
 1   Applicant_Income    950 non-null    float64
 2   Coapplicant_Income  950 non-null    float64
 3   Employment_Status   950 non-null    object
 4   Age                 950 non-null    float64
 5   Marital_Status      950 non-null    object
 6   Dependents          950 non-null    float64
 7   Credit_Score        950 non-null    float64
 8   Existing_Loans      950 non-null    float64
 9   DTI_Ratio           950 non-null    float64
 10  Savings             950 non-null    float64
 11  Collateral_Value    950 non-null    float64
 12  Loan_Amount         950 non-null    float64
 13  Loan_Term           950 non-null    float64
 14  Loan_Purpose        950 non-null    object
 15  Property_Area       950 non-null    object
 16  Education_Level     950 non-null    object
 17  Gender              950 non-null    object
 18  Employer_Category   950 non-null    object
 19  Loan_Approved       950 non-null    object
dtypes: float64(12), object(8)
memory usage: 156.4+ KB

In [174]:
df.describe()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term
count,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000
mean,501.220000,10852.571579,5082.455789,39.971579,1.474737,676.033684,1.950526,0.347263,9940.452632,24802.792632,20522.825263,48.000000
std,289.608451,5061.632859,2943.161570,11.139797,1.105067,71.346015,1.406246,0.144341,5860.736885,14345.696031,11504.142575,24.245322
min,1.000000,2009.000000,1.000000,21.000000,0.000000,550.000000,0.000000,0.100000,65.000000,36.000000,1015.000000,12.000000
25%,250.250000,6730.750000,2472.750000,30.250000,1.000000,616.250000,1.000000,0.220000,4760.250000,12698.250000,9806.250000,24.000000
50%,499.500000,10548.000000,5205.500000,40.000000,1.000000,678.000000,2.000000,0.340000,9880.500000,24321.000000,21210.500000,48.000000
75%,752.750000,15190.000000,7620.750000,49.000000,2.000000,737.000000,3.000000,0.480000,15074.500000,36947.000000,30263.000000,72.000000
max,1000.000000,19988.000000,9996.000000,59.000000,3.000000,799.000000,4.000000,0.600000,19996.000000,49954.000000,39995.000000,84.000000

In [175]:
df.isna().sum()

Applicant_ID          50
Applicant_Income      50
Coapplicant_Income    50
Employment_Status     50
Age                   50
Marital_Status        50
Dependents            50
Credit_Score          50
Existing_Loans        50
DTI_Ratio             50
Savings               50
Collateral_Value      50
Loan_Amount           50
Loan_Term             50
Loan_Purpose          50
Property_Area         50
Education_Level       50
Gender                50
Employer_Category     50
Loan_Approved         50
dtype: int64

In [176]:
categorical_val = df.select_dtypes(include=['object']).columns
Numerical_val = df.select_dtypes(include=['number']).columns

# **Handle Missing Data**

In [177]:
from sklearn.impute import SimpleImputer

In [178]:
X_Imp = SimpleImputer(strategy='mean')
df[Numerical_val] = X_Imp.fit_transform(df[Numerical_val ])
X_Imp = SimpleImputer(strategy='most_frequent')
df[categorical_val] = X_Imp.fit_transform(df[categorical_val ])

In [179]:
df.head()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,48.0,Car,Semiurban,Graduate,Male,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,Business,Urban,Graduate,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,Urban,Graduate,Male,Private,Yes

In [180]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

In [181]:
le=LabelEncoder()
df['Loan_Approved'] = le.fit_transform(df['Loan_Approved'])
df['Education_Level'] = le.fit_transform(df['Education_Level'])

In [182]:
columns= ["Employment_Status", "Marital_Status", "Loan_Purpose", "Property_Area", "Employer_Category","Gender" ]

ohe = OneHotEncoder(drop ='first',sparse_output=False, handle_unknown='ignore')

encoded = ohe.fit_transform(df[columns])

encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(columns), index=df.index)

df = pd.concat([df.drop(columns=columns), encoded_df], axis=1)

In [183]:
df.info(

)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 29 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Applicant_ID                     1000 non-null   float64
 1   Applicant_Income                 1000 non-null   float64
 2   Coapplicant_Income               1000 non-null   float64
 3   Age                              1000 non-null   float64
 4   Dependents                       1000 non-null   float64
 5   Credit_Score                     1000 non-null   float64
 6   Existing_Loans                   1000 non-null   float64
 7   DTI_Ratio                        1000 non-null   float64
 8   Savings                          1000 non-null   float64
 9   Collateral_Value                 1000 non-null   float64
 10  Loan_Amount                      1000 non-null   float64
 11  Loan_Term                        1000 non-null   float64
 12  Education_Level                  1000 non-null   int64
 13  Loan_Approved                    1000 non-null   int64
 14  Employment_Status_Salaried       1000 non-null   float64
 15  Employment_Status_Self-employed  1000 non-null   float64
 16  Employment_Status_Unemployed     1000 non-null   float64
 17  Marital_Status_Single            1000 non-null   float64
 18  Loan_Purpose_Car                 1000 non-null   float64
 19  Loan_Purpose_Education           1000 non-null   float64
 20  Loan_Purpose_Home                1000 non-null   float64
 21  Loan_Purpose_Personal            1000 non-null   float64
 22  Property_Area_Semiurban          1000 non-null   float64
 23  Property_Area_Urban              1000 non-null   float64
 24  Employer_Category_Government     1000 non-null   float64
 25  Employer_Category_MNC            1000 non-null   float64
 26  Employer_Category_Private        1000 non-null   float64
 27  Employer_Category_Unemployed     1000 non-null   float64
 28  Gender_Male                      1000 non-null   float64
dtypes: float64(27), int64(2)
memory usage: 226.7 KB

In [184]:
X = df.drop('Loan_Approved' , axis=1)
y=df['Loan_Approved']

In [185]:
from sklearn.model_selection import train_test_split

In [186]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [187]:
y_train

29     0
535    0
695    0
557    0
836    1
      ..
106    0
270    0
860    0
435    0
102    0
Name: Loan_Approved, Length: 800, dtype: int64

In [188]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,recall_score,f1_score,precision_score

In [189]:
model = LogisticRegression()

In [190]:
model.fit(X_train,y_train)

LogisticRegression()

In [191]:
y_pred = model.predict(X_test)

In [192]:
y_test

521    0
737    0
740    0
660    0
411    0
      ..
408    0
332    0
208    1
613    1
78     0
Name: Loan_Approved, Length: 200, dtype: int64

In [193]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [194]:
print("accuracy_score =",accuracy_score(y_test,y_pred))
print("recall_score =",recall_score(y_test,y_pred))
print("f1_score =",f1_score(y_test,y_pred))
print("precision_score =",precision_score(y_test,y_pred))

accuracy_score = 0.715
recall_score = 0.2459016393442623
f1_score = 0.3448275862068966
precision_score = 0.5769230769230769

In [195]:
from sklearn.neighbors import KNeighborsClassifier

In [196]:
Knn = KNeighborsClassifier()

In [197]:
Knn.fit(X_train,y_train)

KNeighborsClassifier()

In [198]:
y_pred = model.predict(X_test)

In [199]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [200]:
print("accuracy_score =",accuracy_score(y_test,y_pred))
print("recall_score =",recall_score(y_test,y_pred))
print("f1_score =",f1_score(y_test,y_pred))
print("precision_score =",precision_score(y_test,y_pred))

accuracy_score = 0.715
recall_score = 0.2459016393442623
f1_score = 0.3448275862068966
precision_score = 0.5769230769230769